sudo: required
dist: focal
language: go

go:
  - 1.13.x

before_install:
  - sudo apt-get install -y upx

script:
  - make dist
  - make compress
  - make hash

cache:
  directories:
    - $HOME/.cache/go-build        # Cache the binaries
    - $HOME/gopath/pkg/mod         # Cache the Go modules

deploy:
  provider: releases
  api_key:
    secure: gAs2RuvkC4X0xQJWaMgBZ6g9OLp53O1run2w1VkMyGNNUTvGkOzr/EJvqsdN+7V20/CdFqdjomAKwp6djt8o+wqQW35vkOD+ByMZOGitJZ1XKv+WTCzFbCgTkOkoRqJ6lZe9gumy2vyKL75u41CxxSo7hpsfZ0j8jDlN6sIfeLbg3bQ0r7Z/Ql5LLDRKRtPOxpAb06oDWzaGxCn1kurfCJg3h70k7oMDvloWZaAN4titjljOSsVhtcGjAWH4ndFf++qmhHINU2dS8zoaOSLBr271oEgmD0LPDu9qu3Blzar6qBHE1ZWBPG/VojkW4prbuPOb5oNlXPxwhiaNybC/ohfoM/eCsyLsDkZTl1pLMsHSA6JuWwFb+1gxF67N3l2HRVSyvrn0iAuEsOvux9d/U/zxwlarrmLmtGrGIsv7/AhdatJLmqoAQHIsm57eobsOk31YUDjzD9Lk9Lxccn0t3YRR0KlwgOfFjMDjfQjF2OEvqxqhuiEl2jfr83XQz1QX4WznaOjngC5LOKWFjpxQTFmGcTVqxq+spOCdZKMfBnKzNn59Mi2eT0GM6bqKIcFY8pGMlYWC+kLqeTTTAfZxoHDFwla48ZCw8gsERYrd+i+emauRfRw0Q6WRhWTvQb9Fvue/cpl3A3OBykZkkCsjIOS9aQRRboYf+vupK7yv3N4=
  file_glob: true
  file:
    - dist/*
  skip_cleanup: true
  on:
    tags: true